workspace = { members = ["to_query"] }
[package]
name = "struct_to_query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[dependencies]
to_query = {path = "to_query"}